# Generated by Django 3.0.5 on 2020-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200424_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_history',
            name='receipt',
            field=models.FileField(blank=True, upload_to='checkout_files'),
        ),
    ]
