# Generated by Django 3.0.5 on 2020-04-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_buy_history_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.FileField(upload_to='checkout_files')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='checkout_files')),
            ],
        ),
    ]
