# Generated by Django 3.0.5 on 2020-04-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_name',
            new_name='name',
        ),
    ]
