# Generated by Django 3.0.5 on 2020-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_auto_20200424_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='bpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='key',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
