# Generated by Django 3.0.5 on 2020-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_auto_20200425_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease_option',
            name='license',
        ),
        migrations.AlterField(
            model_name='beat',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
