# Generated by Django 3.0.5 on 2020-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_auto_20200425_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease_option',
            name='after_views',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='lease_option',
            name='percent_after_views',
            field=models.IntegerField(null=True),
        ),
    ]
