# Generated by Django 2.2.7 on 2020-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0011_auto_20200501_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='img_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='beat_covers'),
        ),
    ]
