# Generated by Django 3.0.5 on 2020-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('artist', models.CharField(max_length=999)),
                ('role', models.CharField(max_length=999)),
                ('youtube_url', models.CharField(blank=True, max_length=999)),
                ('soundcloud_url', models.CharField(blank=True, max_length=999)),
                ('spotify_url', models.CharField(blank=True, max_length=999)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
