# Generated by Django 3.0.5 on 2020-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20200422_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_stats',
            name='youtube_comments',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
