# Generated by Django 3.0.5 on 2020-04-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_release_stats_youtube_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release_stats',
            name='youtube_comments',
        ),
    ]
