# Generated by Django 3.0.5 on 2020-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_remove_release_stats_youtube_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_stats',
            name='soundcloud_comments',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
