# Generated by Django 3.0.5 on 2020-04-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
                ('youtube_views', models.CharField(blank=True, max_length=999)),
                ('youtube_likes', models.CharField(blank=True, max_length=999)),
                ('youtube_dislikes', models.CharField(blank=True, max_length=999)),
                ('soundcloud_views', models.CharField(blank=True, max_length=999)),
                ('soundcloud_likes', models.CharField(blank=True, max_length=999)),
                ('soundcloud_reposts', models.CharField(blank=True, max_length=999)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.Release')),
            ],
        ),
    ]
