# Generated by Django 3.0.5 on 2020-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_release_stats_soundcloud_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='genre',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
