# Generated by Django 3.0.5 on 2020-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_auto_20200430_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease_option',
            name='random_str',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
