# Generated by Django 3.0.5 on 2020-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_lease_option_random_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_option',
            name='random_str',
            field=models.CharField(default='4BZWB395WWER41FA5I2FR56YBI9QWMNH', max_length=999),
        ),
    ]
