# Generated by Django 3.0.5 on 2020-04-30 20:51

import beats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_auto_20200430_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_option',
            name='random_str',
            field=models.CharField(default=beats.models.id_generator, max_length=999),
        ),
    ]
