# Generated by Django 3.0.5 on 2020-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=999)),
                ('mugshot', models.FileField(upload_to='contact')),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=999)),
                ('img_url', models.CharField(blank=True, max_length=999)),
                ('img', models.FileField(blank=True, null=True, upload_to='contact')),
            ],
        ),
    ]
