# Generated by Django 3.0.5 on 2020-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('shopping_cart', models.TextField(blank=True)),
                ('shopping_cart_total', models.IntegerField()),
                ('buyer_first_name', models.CharField(blank=True, max_length=999)),
                ('buyer_last_name', models.CharField(blank=True, max_length=999)),
                ('buyer_artist_name', models.CharField(blank=True, max_length=999)),
                ('buyer_email', models.CharField(blank=True, max_length=999)),
                ('buyer_address', models.CharField(blank=True, max_length=999)),
            ],
        ),
    ]
