# Generated by Django 3.0.5 on 2020-04-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_history',
            name='shopping_cart_total',
            field=models.FloatField(),
        ),
    ]
