# Generated by Django 3.0.5 on 2020-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200426_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=999)),
            ],
        ),
    ]
