# Generated by Django 3.0.5 on 2020-04-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_mail_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sripe_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, default='Test', max_length=999)),
                ('public_key', models.CharField(max_length=999)),
                ('private_key', models.CharField(max_length=999)),
            ],
        ),
    ]
