# Generated by Django 3.0.5 on 2020-04-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_sripe_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sripe_key',
            new_name='Stripe_key',
        ),
    ]
