# Generated by Django 2.2.7 on 2020-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20200507_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company',
            field=models.CharField(default='Emart Auto OÜ', max_length=999),
        ),
    ]
