# Generated by Django 3.0.5 on 2020-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
